spring:
  application:
    name: async-job-platform

  datasource:
    url: jdbc:postgresql://localhost:5433/notification_db
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    root: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

app:
  notification:
    max-retry: 3
    default-sender: noreply@asyncjob.com